# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import example_pb2 as example__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in example_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CommunicatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UnaryHello = channel.unary_unary(
                '/example.Communicator/UnaryHello',
                request_serializer=example__pb2.HelloRequest.SerializeToString,
                response_deserializer=example__pb2.HelloReply.FromString,
                _registered_method=True)
        self.SplitWords = channel.unary_stream(
                '/example.Communicator/SplitWords',
                request_serializer=example__pb2.TextRequest.SerializeToString,
                response_deserializer=example__pb2.WordReply.FromString,
                _registered_method=True)
        self.Average = channel.stream_unary(
                '/example.Communicator/Average',
                request_serializer=example__pb2.NumberRequest.SerializeToString,
                response_deserializer=example__pb2.AverageReply.FromString,
                _registered_method=True)
        self.Chat = channel.stream_stream(
                '/example.Communicator/Chat',
                request_serializer=example__pb2.ChatMessage.SerializeToString,
                response_deserializer=example__pb2.ChatMessage.FromString,
                _registered_method=True)


class CommunicatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UnaryHello(self, request, context):
        """Unary call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SplitWords(self, request, context):
        """Server-streaming call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Average(self, request_iterator, context):
        """Client-streaming call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request_iterator, context):
        """Bidirectional streaming call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommunicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UnaryHello': grpc.unary_unary_rpc_method_handler(
                    servicer.UnaryHello,
                    request_deserializer=example__pb2.HelloRequest.FromString,
                    response_serializer=example__pb2.HelloReply.SerializeToString,
            ),
            'SplitWords': grpc.unary_stream_rpc_method_handler(
                    servicer.SplitWords,
                    request_deserializer=example__pb2.TextRequest.FromString,
                    response_serializer=example__pb2.WordReply.SerializeToString,
            ),
            'Average': grpc.stream_unary_rpc_method_handler(
                    servicer.Average,
                    request_deserializer=example__pb2.NumberRequest.FromString,
                    response_serializer=example__pb2.AverageReply.SerializeToString,
            ),
            'Chat': grpc.stream_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=example__pb2.ChatMessage.FromString,
                    response_serializer=example__pb2.ChatMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'example.Communicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('example.Communicator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Communicator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UnaryHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/example.Communicator/UnaryHello',
            example__pb2.HelloRequest.SerializeToString,
            example__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SplitWords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/example.Communicator/SplitWords',
            example__pb2.TextRequest.SerializeToString,
            example__pb2.WordReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Average(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/example.Communicator/Average',
            example__pb2.NumberRequest.SerializeToString,
            example__pb2.AverageReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/example.Communicator/Chat',
            example__pb2.ChatMessage.SerializeToString,
            example__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
