# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: example.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'example.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x07\x65xample\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x19\n\tWordReply\x12\x0c\n\x04word\x18\x01 \x01(\t\"\x1f\n\rNumberRequest\x12\x0e\n\x06number\x18\x01 \x01(\x02\"\x1f\n\x0c\x41verageReply\x12\x0f\n\x07\x61verage\x18\x01 \x01(\x02\"+\n\x0b\x43hatMessage\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t2\xf6\x01\n\x0c\x43ommunicator\x12\x38\n\nUnaryHello\x12\x15.example.HelloRequest\x1a\x13.example.HelloReply\x12\x38\n\nSplitWords\x12\x14.example.TextRequest\x1a\x12.example.WordReply0\x01\x12:\n\x07\x41verage\x12\x16.example.NumberRequest\x1a\x15.example.AverageReply(\x01\x12\x36\n\x04\x43hat\x12\x14.example.ChatMessage\x1a\x14.example.ChatMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=26
  _globals['_HELLOREQUEST']._serialized_end=54
  _globals['_HELLOREPLY']._serialized_start=56
  _globals['_HELLOREPLY']._serialized_end=85
  _globals['_TEXTREQUEST']._serialized_start=87
  _globals['_TEXTREQUEST']._serialized_end=114
  _globals['_WORDREPLY']._serialized_start=116
  _globals['_WORDREPLY']._serialized_end=141
  _globals['_NUMBERREQUEST']._serialized_start=143
  _globals['_NUMBERREQUEST']._serialized_end=174
  _globals['_AVERAGEREPLY']._serialized_start=176
  _globals['_AVERAGEREPLY']._serialized_end=207
  _globals['_CHATMESSAGE']._serialized_start=209
  _globals['_CHATMESSAGE']._serialized_end=252
  _globals['_COMMUNICATOR']._serialized_start=255
  _globals['_COMMUNICATOR']._serialized_end=501
# @@protoc_insertion_point(module_scope)
